MODULE GNU_SP_MOD

USE PARKIND1, ONLY : JPRB, JPIM, JPIB

IMPLICIT NONE

CONTAINS

SUBROUTINE INIT

USE FIELD_DEFAULTS_MODULE

REAL (KIND=JPRB), TARGET    :: PTYPE_GP (1, 1, 1, 1)
REAL (KIND=4), POINTER:: POINTER4(:,:,:,:)
REAL (KIND=8), POINTER:: POINTER8(:,:,:,:)
REAL (KIND=JPRB), POINTER:: POINTERJPRB(:,:,:,:)

POINTERJPRB => PTYPE_GP
#ifdef PARKIND1_SINGLE
POINTER4 => PTYPE_GP
#else
POINTER8 => PTYPE_GP
#endif

END SUBROUTINE INIT

END MODULE GNU_SP_MOD

PROGRAM GNU_SP
 USE GNU_SP_MOD
 CALL  INIT
END PROGRAM GNU_SP
